<?xml version="1.0"?>
<robot name="krabby"
  xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="properties.xacro"/>
  <xacro:include filename="materials.xacro"/>
  <xacro:include filename="krabby.gazebo"/>
  <xacro:include filename="macros.xacro"/>

  <link name="base_link"/>

  <!-- ************************************************************** -->
  <!-- chassis                                                        -->
  <!-- ************************************************************** -->
  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
    <origin xyz="0 0 ${chassisDistanceAuSol}" rpy="0 0 0"/>
  </joint>

  <link name='chassis'>
    <collision>
      <geometry>
        <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
      </geometry>
    </collision>
    <visual>
      <geometry>
        <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <inertial>
      <mass value="${chassisMass}"/>
      <xacro:box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}" z="${chassisHeight}"/>
    </inertial>
  </link>

  <!-- ************************************************************** -->
  <!-- body                                                        -->
  <!-- ************************************************************** -->
  <joint name="body_joint" type="fixed">
    <parent link="chassis"/>
    <child link="body"/>
    <origin xyz="${bodyOffsetX} ${bodyOffsetY} ${bodyOffsetZ}"/>
  </joint>

  <link name='body'>
    <collision>
      <geometry>
        <box size="${bodyLength} ${bodyWidth} ${bodyHeight}"/>
      </geometry>
    </collision>
    <!--Kraboss_base_assembly_For_Simu_v1.stl-->
    <visual>
      <geometry>
        <!--<origin xyz="0 ${chassisWidth}/2 ${chassisDistanceAuSol}" rpy="0 0 0"/>-->
        <!--<mesh><uri>file://Kraboss_base_assembly_For_Simu_v1.stl</uri></mesh>-->
        <!--<pose>0 ${chassisWidth}/2 0 0 -0 0</pose>-->
        <mesh scale="0.001 0.001 0.001" filename="file://$(find krabby_description)/models/Kraboss_base_assembly_For_Simu_v1.stl"/>
        <!--<mesh scale="0.001 0.001 0.001" filename="file://$(find krabby_description)/models/Kraboss_base_assembly_For_Simu_v1.dae"/>-->
        <!--<box size="${bodyLength} ${bodyWidth} ${bodyHeight}"/>-->
      </geometry>
      <material name="blue"/>
    </visual>
    <inertial>
      <mass value="${bodyMass}"/>
      <xacro:box_inertia m="${bodyMass}" x="${bodyLength}" y="${bodyWidth}" z="${bodyHeight}"/>
    </inertial>
  </link>

  <!-- ************************************************************** -->
  <!-- wheels                                                      -->
  <!-- ************************************************************** -->
  <xacro:wheel lr="left" parent="chassis" tX="${wheelXOffset}" tY="${wheelYOffset}" tZ="${wheelZOffset}"/>
  <xacro:wheel lr="right" parent="chassis" tX="${wheelXOffset}" tY="${-wheelYOffset}" tZ="${wheelZOffset}"/>

  <xacro:caster_wheel parent="chassis" name="caster_fr" tX="${casterXOffset}" tY="-${casterYOffset}"/>
  <xacro:caster_wheel parent="chassis" name="caster_fl" tX="${casterXOffset}" tY="${casterYOffset}"/>
  <xacro:caster_wheel parent="chassis" name="caster_rr" tX="-${casterXOffset}" tY="-${casterYOffset}"/>
  <xacro:caster_wheel parent="chassis" name="caster_rl" tX="-${casterXOffset}" tY="${casterYOffset}"/>

  <!-- ************************************************************** -->
  <!-- lidar                                                           -->
  <!-- ************************************************************** -->
  <joint name="lidar_joint" type="fixed">
    <parent link="body"/>
    <child link="lidar"/>
    <origin xyz="0 0 ${lidarZPos}"/>
  </joint>

  <link name='lidar'>
    <inertial>
      <mass value="${lidarMass}"/>
      <xacro:cylinder_inertia m="${lidarMass}" r="${lidarRadius}" h="${lidarHeight}"/>
    </inertial>

    <!-- No collision on purpose, to not block lidar rays in simulation -->

    <!-- <collision name="lidar_collision"> -->
    <!--   <pose>0 0 0 0 0 0</pose> -->
    <!--   <geometry> -->
    <!--     <cylinder length="${lidarHeight}" radius="${lidarRadius}"/> -->
    <!--   </geometry> -->
    <!-- </collision> -->

    <visual name="lidar_visual">
      <pose>0 0 0 0 0 0</pose>
      <geometry>
        <cylinder length="${lidarHeight}" radius="${lidarRadius}"/>
      </geometry>
      <material name="black"/>
    </visual>

  </link>


  <!-- ************************************************************** -->
  <!-- camera                                                           -->
  <!-- ************************************************************** -->

  <!-- ************************************************************** -->
  <!-- aruco                                                           -->
  <!-- ************************************************************** -->

  <!-- ************************************************************** -->
  <!-- the following is optional, not corrected yet                    -->
  <!-- ************************************************************** -->
  <link name="aruco_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.001"/>
      <xacro:box_inertia m="0.001" x="${arucoSize}" y="${arucoSize}" z="0.001"/>
    </inertial>

    <collision name="tag_aruco_collision">
      <pose>0 0 0 0 0 0</pose>
      <geometry>
        <box size="${arucoSize} ${arucoSize} 0.001"/>
      </geometry>
    </collision>

    <visual name="tag_aruco_visual">
      <pose>0 0 0 0 0 0</pose>
      <geometry>
        <mesh filename="package://eurobot2020_gazebo/models/tag_aruco/meshes/tag_aruco.dae"/>
      </geometry>
    </visual>
  </link>

  <joint name="aruco_joint" type="fixed">
    <origin xyz="0 0 0.325" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="aruco_link"/>
  </joint>

  <link name="camera_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <inertial>
      <mass value="${cameraMass}" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <xacro:box_inertia m="${cameraMass}" x="${cameraSize}" y="${cameraSize}" z="${cameraSize}" />
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <origin xyz="${-cameraSize+chassisLength/2} 0 ${cameraSize+wheelRadius+cameraSize/2}" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="camera_link"/>
  </joint>

  <link name="tim_top">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${lidarHeight}" radius="${lidarRadius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${lidarHeight}" radius="${lidarRadius}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${lidarMass}"/>
      <xacro:cylinder_inertia m="${lidarMass}" r="${lidarRadius}" h="${lidarHeight}"/>
    </inertial>
  </link>

  <joint name="tim_top_joint" type="fixed">
    <origin xyz="0 0 ${lidarZPos}" rpy="3.14159 0 0"/>
    <parent link="chassis"/>
    <child link="tim_top"/>
  </joint>

</robot>
